$(document).ready(function(){
//    这个是log的动画效果
    $("#lo1").hide(0,function(){
        $("#lo2").hide(0,function(){
            $("#lo3").hide(0,function(){
                $("#lo4").hide(0,function(){
                    $("#lo5").hide(0,function(){
                        $("#lo1").show(500,function(){
                            $("#lo2").show(500,function(){
                                $("#lo3").show(500,function(){
                                    $("#lo4").show(500,function(){
                                        $("#lo5").show(500,function(){
                                        });
                                    });
                                });
                            });
                        });
                    });
                });
            });
        });
    });
    //最新作品的滚动播放动画
    $("#workme1").hide(0,function(){
        $("#worker1").click(2000,function(){
            $("#worker1").attr("src","/img/01.jpg");
            $("#workme1").show(500);
        });
    });
    //这个是百度地图的div隐藏
    $("#allmap").hide(0);

    //点击后图片变焦点显示
    $("#slip0").click(function(){
        $("#obj1").hide(0,function(){
            $("#obj1").attr("src","/img/01.jpg").show(0);
        });
    });
    $("#slip1").click(function(){
        $("#obj1").hide(0,function(){
            $("#obj1").attr("src","/img/02.jpg").show(0);
        });
    });
    $("#slip2").click(function(){
        $("#obj1").hide(0,function(){
            $("#obj1").attr("src","/img/03.jpg").show(0);
        });
    });
    //海报右方
    $("#body1").show();
    $("#body2").hide();
    $("#day1").hover(function(){
        $("#day1").css("color","red");
        $("#body2").hide();
        $("#body1").show();
    },function(){
        $("#day1").css("color","#7b7b7b");
    });
    $("#day2").hover(function(){
        $("#day2").css("color","red");
        $("#body1").hide();
        $("#body2").show();
    },function(){
        $("#day2").css("color","#7b7b7b");
    });
    //店招
    $("#body3").show();
    $("#body4").hide();
    $("#day3").hover(function(){
        $("#day3").css("color","red");
        $("#body4").hide();
        $("#body3").show();
    },function(){
        $("#day3").css("color","#7b7b7b");
    });
    $("#day4").hover(function(){
        $("#day4").css("color","red");
        $("#body3").hide();
        $("#body4").show();
    },function(){
        $("#day4").css("color","#7b7b7b");
    });

});


